// Auto-generated TypeScript enums from C++ headers
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_enums.py
// Run 'python scripts/generate_enums.py' to regenerate

// From AlarmLinesService.h
export enum AlarmLineAcquisition {
  /** /< Built-in alarm line (e.g. broadcast line) */
  BuiltIn = 0,
  /** /< Discovered via received genius packet */
  GeniusPacket,
  /** /< Manually added via web interface */
  Manual,
  /** /< Discovered via acoustic device readout */
  Acoustic,
}

// From CC1101Controller.h
export enum Cc1101RadioState {
  /** /< No valid pin configuration; radio not brought up */
  Cc1101RadioUnconfigured = 0,
  /** /< Bring-up in progress */
  Cc1101RadioInitializing,
  /** /< Radio initialized and operating */
  Cc1101RadioOk,
  /** /< Bring-up failed (e.g. chip not found on configured pins) */
  Cc1101RadioError,
}

// From GeniusDevicesService.h
export enum GeniusAlarmEnding {
  /** /< Alarm is currently active */
  AlarmActive = -1,
  /** /< Alarm was ended by smoke detector */
  BySmokeDetector = 0,
  /** /< Alarm was ended manually via web interface */
  ByManual,
  /** /< Alarm was cleared during a device config import */
  ByImport,
}

// From GeniusDevicesService.h
export enum GeniusSmokeDetector {
  /** /< Unknown smoke detector type */
  Unknown = -1,
  /** /< Genius H smoke detector */
  GeniusH = 0,
  /** /< Genius Hx smoke detector */
  GeniusHx = 1,
  /** /< Genius Plus smoke detector */
  GeniusPlus = 2,
  /** /< Genius Plus X smoke detector */
  GeniusPlusX = 3,
}

// From GeniusDevicesService.h
export enum GeniusRadioModule {
  /** /< Unknown radio module type */
  Unknown = -1,
  /** /< No FM radio module */
  None = 0,
  /** /< FM Basis radio module */
  FmBasis = 1,
  /** /< FM Pro radio module */
  FmPro = 2,
  /** /< FM MCP radio module */
  FmMcp = 3,
  /** /< FM Basis X radio module */
  FmBasisX = 4,
  /** /< FM Pro X radio module */
  FmProX = 5,
}

// From GeniusDevicesService.h
export enum GeniusDeviceRegistration {
  /** /< Device is built-in */
  BuiltIn = 0,
  /** /< Device was added via received genius packet */
  GeniusPacket,
  /** /< Device registered manually (via web interface) */
  Manual,
  /** /< Device identified via acoustic (smartsonic) readout */
  Acoustic,
}

// From GeniusGateway.h
export enum GeniusPacketType {
  /** /< Unknown packet type */
  Unknown = -1,
  /** /< Commissioning packet (smoke detector assignment to alarm line) */
  Commissioning = 0,
  /** /< CommissioningProbe request packet (request for smoke detectors to identify) */
  CommissioningProbeRequest,
  /** /< CommissioningProbe response packet (smoke detector identification response) */
  CommissioningProbeResponse,
  /** /< Alarm start packet (smoke detection notification) */
  AlarmStart,
  /** /< Alarm stop packet (smoke cleared or alarm silenced) */
  AlarmStop,
  /** /< Line test start packet (line test initiation) */
  LineTestStart,
  /** /< Line test stop packet (line test completion) */
  LineTestStop,
  /** /< NeighborProbe request (radio module 0x55-family, subtype 0x06; direct-range probe) */
  NeighborProbeRequest,
  /** /< NeighborProbe response (radio module 0x55-family, subtype 0x08; carries responder group/line + status) */
  NeighborProbeResponse,
}

// From cc1101.h
export enum Cc1101Mode {
  Idle = 0,
  Rx,
  Tx,
}
