// Auto-generated TypeScript enums from C++ headers
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_enums.py
// Run 'python scripts/generate_enums.py' to regenerate

// From AlarmLinesService.h
export enum AlarmLineAcquisition {
  /** Alarm line built-in (e.g. broadcast) */
  BuiltIn = 0,
  /** Alarm line added via received genius packet */
  GeniusPacket,
  /** Alarm line added manually (via web interface) */
  Manual,
}

// From cc1101.h
export enum Cc1101Mode {
  Idle = 0,
  Rx,
  Tx,
}

// From GatewayDevicesService.h
export enum GeniusAlarmEnding {
  /** Alarm is currently active */
  AlarmActive = -1,
  /** Alarm was ended by smoke detector */
  BySmokeDetector = 0,
  /** Alarm was ended by manual reset */
  ByManualReset,
}

// From GatewayDevicesService.h
export enum GeniusSmokeDetector {
  /** Unknown smoke detector type */
  Unknown = -1,
  GeniusPlusX = 0,
}

// From GatewayDevicesService.h
export enum GeniusRadioModule {
  /** Unknown radio module type */
  Unknown = -1,
  FmBasisX = 0,
}

// From GatewayDevicesService.h
export enum GeniusDeviceRegistration {
  /** Device is built-in */
  BuiltIn = 0,
  /** Device was added via received genius packet */
  GeniusPacket,
  /** Device registered manually (via web interface) */
  Manual,
}

// From GeniusGateway.h
export enum GeniusPacketType {
  /** Unknown packet type */
  Unknown = -1,
  /** Commissioning packet (comissioning of smoke detectors to an alarm line) */
  Commissioning = 0,
  /** Discovery request packet (request for smoke detectors to self identify) */
  DiscoveryRequest,
  /** Discovery response packet (response from smoke detectors with their IDs) */
  DiscoveryResponse,
  /** Alarm start packet (indicating smoke has been detected) */
  AlarmStart,
  /** Alarm stop packet (indicating smoke has been cleared or alarm has been silenced) */
  AlarmStop,
  /** Line test start packet (indicating a line test has been started) */
  LineTestStart,
  /** Line test stop packet (indicating a line test has been stopped) */
  LineTestStop,
}
