// Auto-generated TypeScript enums from C++ headers
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_enums.py
// Run 'python scripts/generate_enums.py' to regenerate

// From AlarmLinesService.h
export enum AlarmLineAcquisition {
  /** /< Built-in alarm line (e.g. broadcast line) */
  BuiltIn = 0,
  /** /< Discovered via received genius packet */
  GeniusPacket,
  /** /< Manually added via web interface */
  Manual,
}

// From cc1101.h
export enum Cc1101Mode {
  Idle = 0,
  Rx,
  Tx,
}

// From GatewayDevicesService.h
export enum GeniusAlarmEnding {
  /** /< Alarm is currently active */
  AlarmActive = -1,
  /** /< Alarm was ended by smoke detector */
  BySmokeDetector = 0,
  /** /< Alarm was ended manually via web interface */
  ByManual,
}

// From GatewayDevicesService.h
export enum GeniusSmokeDetector {
  /** /< Unknown smoke detector type */
  Unknown = -1,
  /** /< Genius Plus X smoke detector model */
  GeniusPlusX = 0,
}

// From GatewayDevicesService.h
export enum GeniusRadioModule {
  /** /< Unknown radio module type */
  Unknown = -1,
  /** /< FM Basis X radio module model */
  FmBasisX = 0,
}

// From GatewayDevicesService.h
export enum GeniusDeviceRegistration {
  /** /< Device is built-in */
  BuiltIn = 0,
  /** /< Device was added via received genius packet */
  GeniusPacket,
  /** /< Device registered manually (via web interface) */
  Manual,
}

// From GeniusGateway.h
export enum GeniusPacketType {
  /** /< Unknown packet type */
  Unknown = -1,
  /** /< Commissioning packet (smoke detector assignment to alarm line) */
  Commissioning = 0,
  /** /< Discovery request packet (request for smoke detectors to identify) */
  DiscoveryRequest,
  /** /< Discovery response packet (smoke detector identification response) */
  DiscoveryResponse,
  /** /< Alarm start packet (smoke detection notification) */
  AlarmStart,
  /** /< Alarm stop packet (smoke cleared or alarm silenced) */
  AlarmStop,
  /** /< Line test start packet (line test initiation) */
  LineTestStart,
  /** /< Line test stop packet (line test completion) */
  LineTestStop,
}
