import type { Plugin } from 'vite';
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const pluginDir = dirname(fileURLToPath(import.meta.url));
const VERSION_TS = resolve(pluginDir, 'src/lib/version.ts');
const VERSION_H = resolve(pluginDir, '../lib/framework/AppVersion.h');

function makeBuildId(now: Date = new Date()): string {
	const pad = (n: number): string => String(n).padStart(2, '0');
	const date = `${now.getUTCFullYear()}${pad(now.getUTCMonth() + 1)}${pad(now.getUTCDate())}`;
	const time = `${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(now.getUTCSeconds())}`;
	return `${date}.${time}`;
}

function readBaseVersion(): string {
	if (process.env.APP_VERSION) return process.env.APP_VERSION;
	try {
		const pkg = JSON.parse(readFileSync(resolve(pluginDir, 'package.json'), 'utf8'));
		return typeof pkg.version === 'string' ? pkg.version : '0.0.0-dev';
	} catch {
		return '0.0.0-dev';
	}
}

function writeIfChanged(path: string, content: string): boolean {
	try {
		const existing = readFileSync(path, 'utf8');
		if (existing === content) return false;
	} catch {
		// file missing; fall through to write
	}
	mkdirSync(dirname(path), { recursive: true });
	writeFileSync(path, content, 'utf8');
	return true;
}

export default function viteAppVersion(): Plugin {
	return {
		name: 'vite-plugin-app-version',
		apply: 'build',
		buildStart() {
			const base = readBaseVersion();
			const buildId = makeBuildId();
			const full = `${base}-${buildId}`;

			const tsBody =
				`// AUTO-GENERATED FILE — DO NOT EDIT.\n` +
				`// Regenerated by vite-plugin-app-version on every frontend build.\n` +
				`// Combines APP_VERSION from platformio.ini with a UTC build timestamp\n` +
				`// (YYYYMMDD.HHMMSS) so any change to the embedded frontend produces\n` +
				`// a new identifier. Compared against the version reported by the\n` +
				`// firmware over the event WebSocket to detect stale cached UIs.\n` +
				`export const APP_VERSION_FULL = ${JSON.stringify(full)};\n`;
			const hBody =
				`// AUTO-GENERATED FILE — DO NOT EDIT.\n` +
				`// Regenerated by vite-plugin-app-version on every frontend build.\n` +
				`#pragma once\n` +
				`#define APP_VERSION_FULL "${full}"\n`;

			writeIfChanged(VERSION_TS, tsBody);
			writeIfChanged(VERSION_H, hBody);

			this.info?.(`APP_VERSION_FULL = ${full}`);
		}
	};
}
