"""
Pre-build guard: write a stub AppVersion.h if it is missing.

AppVersion.h is generated by vite-plugin-app-version during the frontend
build (build_interface.py). When the frontend build is skipped because
WWWData.h is already up-to-date, the header is never regenerated -- which
breaks the C++ compiler if AppVersion.h was absent (e.g. after a fresh
clone or gitignore removal).

This script runs before build_interface.py and ensures the header always
exists. The real build overwrites the stub with the actual timestamp.
"""

import os
import sys

from prebuild_utils import is_build_task

if not is_build_task(['build', 'upload', 'buildfs', 'erase_upload']):
    print("Skipping ensure_app_version for non-build task.")
    sys.exit(0)

Import("env")

project_dir = env["PROJECT_DIR"]
header_path = os.path.join(project_dir, "lib", "framework", "AppVersion.h")

if not os.path.exists(header_path):
    stub = (
        '// AUTO-GENERATED FILE — DO NOT EDIT.\n'
        '// Stub written by ensure_app_version.py; overwritten by the frontend build.\n'
        '#pragma once\n'
        '#define APP_VERSION_FULL "0.0.0-00000000.000000"\n'
    )
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, "w") as f:
        f.write(stub)
    print(f"ensure_app_version: wrote stub {header_path}")
else:
    print(f"ensure_app_version: {header_path} already exists, skipping.")
