// AUTO-GENERATED FILE — DO NOT EDIT.
// Regenerated by vite-plugin-app-version on every frontend build.
// Committed stub value; the real value is written at build time.
export const APP_VERSION_FULL = '0.0.0-dev';
